config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :pictures, only:[:new, :create]

  #devise_for :views
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks'}

  #nancy did this below : These are for creating shotcut routes. so localhost:3000/login goes to 'devise/sessions#new'. Must make sure links reflect change
   devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'devise/sessions#destroy'
    get 'dashboard', to: 'application#dashboard'
   end
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post] #Do i need?
  root to: 'application#welcome'

  resources :categories, only: [:new, :create]

  resources :pictures do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
  
  get '/gallery', to: 'pictures#gallery', as: 'gallery'
  post '/gallery', to: 'pictures#filter', as: 'filter'
  

end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :comments, as: :commentable, dependent: :destroy
    has_one_attached :image, dependent: :destroy
    scope :category_filter, -> (category_id) { where(category_id: category_id) }
    scope :owned_pictures, -> (user) { where(user_id: user.id) }



    validates :title, presence: true
    validate :must_have_image

    def self.newest_5
        last(5).reverse
    end
    
    def get_authorname
        self.user.name
    end

    def category_attributes=(attributes)
        #{"animal_type" => "Cat"}
        if attributes["animal_type"].present?
            attributes.values.each do |animal_type|
                animal_type.capitalize!
                category = Category.find_or_create_by(:animal_type => animal_type)
                self.category = category
            end
        end
    end

    private
    def must_have_image
        errors.add(:image, "must have an image!") if !self.image.attached?
    end
end

app/controllers/picture_controller.rb
class PictureController < ApplicationController
    before_action :require_login, only: [:new, :create, :index]

    def new
        binding.pry
    end

    def create
        @picture = Picture.new(picture_params)
        if @picture.save
           session[:picture_id] = @picture.id
           redirect_to picture_path(@picture)
        else
           flash[:errors] = @picture.errors.full_message
           redirect_to new_picture_path(@picture)
        end
    end
    
    def show

    end

    def index
        #shows user's pictures
        binding.pry
        @pictures = Picture.where(user_id: current_user.id)

    end

    def gallery
        #shows all pictures
        @pictures = Picture.all
    end


    private
    
    def picture_params
        params.require[:picture].permit(:title, :description, :image)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    before_action :require_login, except: [:gallery, :filter]
    before_action :set_picture, only: [:show, :edit, :update, :destroy]
    before_action :allowed_to_modify?, only: [:edit, :update, :destroy]



    def new
        @picture = Picture.new
    end

    def create
         @picture = current_user.pictures.build(picture_params)
         if @picture.image.attach(params[:picture][:image]) && @picture.save
           redirect_to picture_path(@picture)
        else
           render :new
        end
    end
    
    def show
        @comment = Comment.new
    end

    def edit
    end

    def update
        if @picture.update(picture_params)
            redirect_to picture_path(@picture)
        else
            render :edit
        end
    end

    def index
        #shows user's pictures
        @pictures = Picture.where(user_id: current_user.id)

    end

    def gallery
        #shows all pictures, does NOT require login
        @pictures = Picture.all
    end

    def filter
        #params[:filter][:category_id] => ["", "1", "3", "4"] First is ALWAYS "" is hidden value -- Can't figure out what reason it's making a hidden field
        filters = params[:filter][:category_id].collect{ |c_id| next if c_id.empty?; c_id}.compact
        if  filters.count > 0
            @pictures = Picture.category_filter(filters)
            render :gallery
        else
            @pictures = Picture.all
            render :gallery
        end
    end

    
    def destroy
        @picture.destroy
        redirect_to pictures_path
    end


    private
    
    def picture_params
        params.require(:picture).permit(:title, :description, :image, :category_id, category_attributes:[:animal_type])
    end
    def set_picture
        @picture = Picture.find_by(id: params[:id])
    end
    
 
    def allowed_to_modify?
        if !owns_picture?
            flash[:error] = "You can only edit your own pictures."
            redirect_back(fallback_location: root_path) 
        end
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for picture do |f| %>
    <%= image_tag picture.image.variant(resize_to_limit: [800, 500]) if picture.image.attached? %><br>
    
    <%= f.text_field :title, placeholder: "Title" %><br>
        
    
    <p><%= f.label :description %>:</p>
    <%= f.text_area :description %><br><br>
    
    <%= f.label "Category:" %>
    <%= collection_select(:picture, :category_id, Category.all, :id, :animal_type, :include_blank => "Make New") %>
    <%# New Category Fields %>
        <p><%= f.fields_for :category, Category.new do |new_animal_type| %>
        <%= new_animal_type.label :animal_type, "New category:" %>
        <%= new_animal_type.text_field :animal_type %>

    <% end %></p><br>
    

    <p><%= f.file_field :image  if !picture.image.attached?%></p>
    <%= f.submit %>
    
<% end %>
<br><br>
<%= button_to "Delete Page", picture_path(picture), method: :delete if picture.valid? %>
<%= link_to 'Back', :back %>

app/views/pictures/edit.html.erb
<%= render partial: 'layouts/error_messages', locals: {object: @picture} %>
<%= render 'form', picture: @picture %>

app/views/pictures/gallery.html.erb
<h1>Gallery Page</h1>

<p>"Choose a filter:" </p>
<%= form_tag gallery_path do %>
    <p><%= collection_select(:filter, :category_id, Category.all.order("animal_type ASC"), :id, :animal_type, {:include_blank => false}, {:multiple => true}) %></p>
    <%= submit_tag "Select Filter" %>
<% end %>




<div class=flex-picture_gallery>
    <% @pictures.each do |picture| %>
    
        <%= link_to picture_path(picture) do %>
            <%= render partial: "layouts/picture", locals: {picture: picture, type: "list"} %>
        <% end %>
        
    <% end %>
</div> <%# flex-picture_gallery %>

<%= link_to 'Back', :back %>

app/views/pictures/index.html.erb
<h1>Index page PictureController#index</h1>
<% @pictures.each do |picture| %>
    <%= link_to picture_path(picture) do %>
        <%= render partial: "layouts/picture", locals: {picture: picture, width:600, height:600} %>
    <% end %>

    <br><br><strong> ----------------------------------------------------</strong>
<% end %><br>

<%= link_to 'Back', :back %>

app/views/pictures/new.html.erb
<h1>New pics</h1>
<%= render partial: 'layouts/error_messages', locals: {object: @picture} %>
<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<h1>Show page</h1>
<%= render partial: "layouts/picture", locals: {picture: @picture, width:nil, height:500} %>
<%= button_to "Edit Info", edit_picture_path(@picture), method: :get if owns_picture?%>
<%# comment section %>
<%= render partial: 'layouts/error_messages', locals: {object: @comment} %>
<h2>Comments</h2>

<%= form_for [@picture, @comment] do |f| %>
    <%= f.text_area :content, placeholder: "Add a comment" %><br>
    <%= f.submit "Add Comment" %>
<% end %>
<div class=flex-holder><ul>
    <%= render partial: 'layouts/comment', collection: @picture.comments %>
</ul></div>
<%= link_to 'Back', :back %>