config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :pictures, only:[:new, :create]

  #devise_for :views
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks'}

  #nancy did this below : These are for creating shotcut routes. so localhost:3000/login goes to 'devise/sessions#new'. Must make sure links reflect change
   devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'devise/sessions#destroy'
    get 'dashboard', to: 'application#dashboard'
   end
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post] #Do i need?
  root to: 'application#welcome'

  resources :categories, only: [:new, :create]

  resources :pictures do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
  
  get '/gallery', to: 'pictures#gallery', as: 'gallery'
  post '/gallery', to: 'pictures#filter', as: 'filter'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login, only: [:dashboard]
    helper_method :owns_comment?
    helper_method :owns_picture?

    def welcome
        #Into to application
        @pictures = Picture.newest_5
    end

    def dashboard
        #Must be logged in
        #Comes here from Account Settings
        @pictures = Picture.owned_pictures(current_user)
        @comments = Comment.new_since_login(current_user).comments_from_pictures #.not_deleted to be implemented in next version
        

    end

    private
    def require_login
        redirect_to '/signup' unless current_user
    end

    def owns_picture?
        @picture ||= @comment.get_picture
        current_user.pictures.include?(@picture)
    end

    def owns_comment?
        comment = Comment.find(params[:id])
        !!(comment.user == current_user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/dashboard.html.erb
<h1>Account Dashboard</h1>
<h1> <%= current_user.username %> Dashboard</h1>
<h4>Newest 5 pictures:</h4>
<div class=flex-holder>
    <% @pictures.newest_5.each do |picture| %>
        <%= link_to picture_path(picture) do %>
            <div class = flex-container>
                <%= render partial: "layouts/picture", locals: {picture: picture, type: "list"} %>
                <%= render partial: "layouts/comment", locals: {comments: picture.comments, type: "preview"} %>
            </div><%#flex-container %>
        <% end %>
        
    <% end %>
</div> <%# flex-holder %>
<h4>New comments since your last visit</h4>
<%= render partial: "layouts/comment", locals: {comments: @comments, type: "preview"} %>
 <br><br>
<%= link_to "More pictures...", pictures_path %><br>
<%= link_to "Add picture", new_picture_path %>

<br><br>

app/views/application/welcome.html.erb
<h1>Welcome to RateMyPet</h1>
<p>This website is spinoff to the classic "Rate my <em>whatever</em>" websites of the early 2000's and today</p>
<br>
<h3>Come browse our pets gallery, where you can search based on animal, *popularity, or *whatever's new</h2>
<%# Does this turn into a partial? How would I differentiate inner partials %>
<div class=flex-picture_gallery>
    <% @pictures.each do |picture| %>
    
        <%= link_to picture_path(picture) do %>
            <%= render partial: "layouts/picture", locals: {picture: picture, type: "list"} %>
        <% end %>
        
    <% end %>
</div> <%# flex-holder %>
<%= link_to "Go to gallery!", gallery_path %><br>

<small><small><small><small>*Not all features are included at initial release</small></small></small></small>