config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :pictures, only:[:new, :create]

  #devise_for :views
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'callbacks'}

  #nancy did this below : These are for creating shotcut routes. so localhost:3000/login goes to 'devise/sessions#new'. Must make sure links reflect change
   devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'devise/sessions#destroy'
    get 'dashboard', to: 'application#dashboard'
   end
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post] #Do i need?
  root to: 'application#welcome'

  resources :categories, only: [:new, :create]

  resources :pictures do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
  
  get '/gallery', to: 'pictures#gallery', as: 'gallery'
  post '/gallery', to: 'pictures#filter', as: 'filter'
  

end

app/views/layouts/_comment.html.erb
<% if defined?(type) && type == "preview" %>
    <div>

            Has <%= pluralize(comments.count, "comment") %> </small><br>
            <% comments.each do |comment|%>
                <% next if comment.deleted? %>
                <ul><%= link_to(comment.display_content, comment)%> <small>By: <%= comment.get_authorname%> </ul></small>
            <% end %>
    </div>
<% else %>
    <li>
        <p><%= comment.display_content %></p>
        <small>
        <% if comment.deleted? %>
            Comment deleted <br>
            <small>Deleted <%= time_ago_in_words(comment.updated_at) %> ago</small><br>
        <% else %>
            By <%= comment.get_authorname %> <br>
            Submitted <%= time_ago_in_words(comment.created_at) %> ago<br>
            <% if comment.updated_at > comment.created_at %>
                <small>Edited <%= time_ago_in_words(comment.updated_at) %> ago</small><br>
            <% end %>
        <% end %>
        </small>

        <%= form_for [comment, Comment.new] do |f| %>
        <%# hidden_field_tag :picture_id, params[:id] %>
            <% if !comment.deleted? %>
            <%= f.text_area :content, placeholder: "Add a Reply" %><br>
            <%= f.submit "Reply to #{comment.get_authorname}" %>
            <% end %>
        <% end %>
        <%= button_to "Delete Comment", comment_path(comment), method: :delete if comment.user==current_user && !comment.deleted? %>
        <%# button_to "Edit Comment", comment_path(comment), method: :patch if comment.user==current_user && !comment.deleted? %>
        <%# comment replies: COMMENTCEPTION %>
        <ul>
            <%= render partial: "layouts/comment", collection: comment.comments %>
        </ul>

    </li>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <h3>There were some errors:</h3>
        <ul>
        <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav>
    <ul class=nav>
        <li class=nav> <%= link_to "Home", root_path %> </li>
		<li class=nav> <%= link_to "Gallery", gallery_path %>
		<% if !user_signed_in? %>
			<li class=nav><%= link_to "Signup", new_user_registration_path %> </li>
			<li class=nav><%= link_to "Login", new_user_session_path %> </li>
		<% else %>
			<li class=nav><%= link_to "Account Dashboard", dashboard_path %></li>
			<li class=nav><%= link_to "Logout", destroy_user_session_path, method: "delete" %></li>
		<% end %>
    </ul>
</nav>

app/views/layouts/_picture.html.erb
<% if defined?(type) && type=="list"%>
        <div>
            <% if !!defined?(width) || !!defined?(height) %>
                <%= image_tag picture.image.variant(resize_to_limit: [width, height]) %>
            <% else %>
                <%= image_tag picture.image.variant(resize_to_limit: [nil, 300]) %>
            <% end %>
        </div>
        <div>
            <h3 class=flex><%= picture.title %></h3>
            <small>By <%= picture.get_authorname %></small><br>
            <small>Submitted <%= time_ago_in_words(picture.created_at) %> ago<br></small>
        </div>
<% else %>
    <p><% if (!!defined?(width) || !!defined?(height) )%>
        <%= image_tag picture.image.variant(resize_to_limit: [width, height]) %>
    <% else %>
        <%= image_tag picture.image.variant(reize_to_limit: [800, 500]) %>
    <% end %></p>
    <h3 class=flex><%= picture.title %></h3><br>
    <p><%= picture.description %></p>
    <small>Submitted <%= time_ago_in_words(picture.created_at) %> ago<br>
    Has <%= pluralize(picture.comments.count, "comment") %> </small>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateMyPet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>